on: [push, pull_request]

jobs:
  armv8_job:
    runs-on: [self-hosted, linux, ARM64]
    name: Build on self hosted aarch64
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: gleam-lang/setup-erlang@v1.1.2
        with:
          otp-version: "22.x"
          
      # run the prebuild and config scripts  
      - name: run prebuild script
        working-directory: ${{github.workspace}}/app
        run: |
            ./linux-prebuild.sh
      
      - name: run config script
        working-directory: ${{github.workspace}}/app
        run: |
            ./linux-config.sh
            
      - name: run build
        working-directory: ${{github.workspace}}/app/build
        run: |
            cmake --build . --config Release

      # Set an output parameter `uname` for use in subsequent steps
      - run: |
         uname -a
         echo ::set-output name=uname::$(uname -a)

